apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "configmaps", "secrets", "persistentvolumeclaims", "statefulsets", "jobs", "ingresses"]
  verbs: ["get", "list", "watch", "create", "delete"]


